mother-of-all-self-hosting/mash-playbook

docs/services/hubsite.md
group_vars/mash_servers

Fix examples:
- hubsite_service_list_additional
- hubsite_service_list_auto
Update Uptime Kuma description

Fix hubsite example

---

group_vars/mash_servers
requirements.yml

* Radicale
* Syncthing
* Woodpecker CI
* Focalboard
* Docker Registry Browser
* Adguard

Add a bunch of services

---

CHANGELOG.md
docs/services/firezone.md
group_vars/mash_servers
requirements.yml

Breaking change: Firezone

---

group_vars/mash_servers
requirements.yml

* Typo
* Change order of keys in requirements to support Agru

GoToSocial

---

docs/services/owncast.md
docs/supported-services.md
group_vars/mash_servers
requirements.yml
setup.yml

This PR is based on the GoToSocial branch as I hope this PR will be merged soon and I can minimize the time solving merge conflicts

Add Owncast

---

group_vars/mash_servers

Owncast does not support path prefixes

Remove owncast path prefix

---

docs/funkwhale.md
docs/services/funkwhale.md
docs/supported-services.md
group_vars/mash_servers
requirements.yml
setup.yml

So just some comments why I did things the way I did them:
* The frontend container is based on nginx and it is not possible to run as non-root. The actual app in the container runs as user. Also readonly is not really possible (stopped after the 6th mount/tmpfs). The capabilities are dropped as far as possible.
* Postgres is automatically connected, redis isn't (as per playbook standard)
* The manual user creation is needed as django does not allow non-interactive creation of users... *sigh*

Add funkwhale

---

docs/services/mrs.md
docs/supported-services.md
group_vars/mash_servers
requirements.yml
setup.yml

A fully-featured, standalone, matrix rooms search service.
1. Discover matrix servers (a.k.a find alive and properly configured) from provided config
2. Parse public rooms from the discovered servers
3. Ingest parsed public rooms into search index
Each step can be run separately or all at once using admin API
https://gitlab.com/etke.cc/mrs/api/-/blob/main/openapi.yml

add Matrix Rooms Search API

---

group_vars/mash_servers
requirements.yml

Adds a hubsite entry for
* authentik
* Appsmith
* Firezone
* Funkwhale
* Healthchecks
* Keycloak

Add some hubsite services

---

CHANGELOG.md
group_vars/mash_servers
requirements.yml

This is a breaking change which is documented in the changelog

refactor! Use authentik_container as there is only one

---

docs/services/postgres-exporter.md
group_vars/mash_servers
requirements.yml
setup.yml

I ran into some issues with my postgres db lately, as all connections where exceeded. Postgres exporter should help debug&monitor the database. I use a dedicated user to run the monitoring (as running with a superuser would be a security risk).

Postgres exporter

---

group_vars/mash_servers

Should not be postgres port :)

fix backup-borg mariadb port

---

docs/services/telegraf.md
group_vars/mash_servers
requirements.yml
setup.yml

This adds telegraf. I decided to to a setup where telegraf is configured via influxdb as this makes our playbook easier and not deal with the actual configuration.

Add Telegraf

---

docs/services/mosquitto.md
docs/services/rumqttd.md
docs/supported-services.md
group_vars/mash_servers
requirements.yml
setup.yml

Another, mor feature complete MQTT broker

Add mosquitto

---

docs/services/linkding.md
docs/supported-services.md
group_vars/mash_servers
requirements.yml
setup.yml

This PR adds support for Linkding using a custom role I made ([kinduff/ansible-docker-linkding](https://github.com/kinduff/ansible-docker-linkding)).
Works pretty good! Tested SQlite and PostgreSQL as engines, and with and without a path.

Adds support for Linkding

---

bin/feeds.py
justfile
releases.opml

Copy of the script we use to generate feeds in etke.cc/ansible

add OPML generator script

---

docs/services/prometheus-ssh-exporter.md
docs/supported-services.md
group_vars/mash_servers
releases.opml
requirements.yml
setup.yml

based on the blackbox exporter role

add prometheus-ssh-exporter

---

docs/services/forgejo.md
docs/supported-services.md
group_vars/mash_servers
releases.opml
requirements.yml
setup.yml

Adding Forgejo. Let me know if I'm missing something.

Add Forgejo

---

docs/services/freshrss.md
docs/supported-services.md
group_vars/mash_servers
requirements.yml
setup.yml

Adds support for [FreshRSS](https://freshrss.org). I've been running this for a couple weeks and works like a charm.

Adds FreshRSS service

---

templates/requirements.yml

didn't tested it yet, if no one tests it until the weekend i'll test :)

bump nextcloud to v28

---

templates/group_vars_mash_servers
templates/requirements.yml

Add loki to mash.
Before merging, you have to create the 2.8.7 release for ansible-role-loki
then the loki branch can be merged to main

Loki is ready

---

docs/services/languagetool.md
docs/supported-services.md
templates/group_vars_mash_servers
templates/requirements.yml
templates/setup.yml

add https://gitlab.com/etke.cc/roles/languagetool

add Languagetool

---

docs/services/forgejo.md

**Note**: This PR depends on https://github.com/NeonMinnen/ansible-role-forgejo/pull/5
After fiddling quite a bit with this setup, I think it's only fair if
I expand the documentation and explain how to integrate both services.

Better explain how to integrate Forgejo and Woodpecker CI

---

docs/services/adguard-home.md

Make what port to change more explicit so there's a higher correlation between the instructions and the interface people will see.

Make what port to change more explicit

---

docs/services/woodpecker-ci.md

This reflects the changes done at https://github.com/devture/com.devture.ansible.role.woodpecker_ci_agent/commit/8671cf01d1c5e2e7bacdf7708cc517029c771e36

Improve Woodpecker's main docs re. agent secrets

---

docs/services/adguard-home.md

Fix grammar mistakes, improve readability and suggest "systemctl edit".

Improve Adguard Home's Troubleshooting section

---

docs/services/wetty.md
docs/supported-services.md
templates/group_vars_mash_servers
templates/requirements.yml
templates/setup.yml

This PR adds support for [Wetty](https://github.com/butlerx/wetty/tree/main)
This is my first major PR for this repository, so it may be good to through every thing with a fine-toothed comb in-case I missed something by accident !
Everything seems to be working on my end, including serving on custom paths

Add Support for Wetty

---

VERSIONS.md
docs/services/notfellchen.md
templates/group_vars_mash_servers
templates/requirements.yml

Notfellchen is a django app that allows you to manage a list of animals that are up for adoption in order to increase the chances of them finding a home and ease the burden on rescue organizations.
While the software can be deployed in other countries and would be useful for there, the target audience is very limited. So similar to the ILMO role not adding it is totally fine for me

Custom role Notfellchen

---

templates/group_vars_mash_servers

related to https://github.com/mother-of-all-self-hosting/ansible-role-nextcloud/pull/17

added optional systemd timer for nextcloud app updates

---

templates/requirements.yml

Adds support for LSIO Docker mods

Bump Calibre-Web role to v0.6.21-1

---

docs/services/calibre-web.md

This adds documentation how to deal with #215  (coming with PR #216 )

Added doc how to enable ebook converter in calibre web

---

templates/requirements.yml

fix probable typo in requierements.yml

fix: activation_prefix for calibre-web

---

templates/requirements.yml

Upgrade Jitsi (v9584-0 -> v9584-1)

Upgrade Jitsi (v9584-0 -> v9584-1)

---

templates/requirements.yml

I've running .3 for about a week, no issues

 Upgrade Nextcloud (29.0.1-0 -> 29.0.3-0)

---

templates/requirements.yml

Changed my GH username. Updated requirements.

Username Update on requirement.yml

---

templates/requirements.yml

Username Switch. Updating requirements.

Update Requirement Username

---

docs/services/matterbridge.md
docs/supported-services.md
templates/requirements.yml
templates/setup.yml

I have implemented Matterbridge as a service and would like to contribute it.
As this is my first public MASH role, I would be very happy to have some feedback. If it is then considered okay, I would prefer the role to move into the MASH organisation.
I have also integrated the role into the mash-playbook. But I'm not sure if I've thought of everything. I would also be grateful for feedback on this :) 
Best regards
Oliver

Adds Matterbridge service

---

templates/group_vars_mash_servers

I noticed that Navidrome is missing on my hubsite.
This change does not fix that for me, but I think it is part of the fix and I could not find any other obvious thing. So I hope you can point me to what else needs to be changed or add it to this PR yourself?

Add hubsite configuration for Navidrome

---

templates/requirements.yml

Name Updated. 

---

roles/mash/playbook_migration/tasks/validate_config.yml

Fixed confusing suggestion as seen

correct typo of postgres in validate_config.yml

---

docs/services/backup-borg.md
docs/services/writefreely.md
docs/supported-services.md

PR fixes the broken links found in the doc files.

Update broken references

---

VERSIONS.md
docs/services/infisical.md
templates/requirements.yml

- Upgrade Infisical v0.4.2 > v.0.43.19
- Upgrade Nextcloud 30.0.2 > 30.0.4

Update main.yml & requirements for Infisical and nextcloud

---

templates/requirements.yml

version bump
https://codeberg.org/readeck/readeck/releases/tag/0.17.1

readeck version bump to 0.17.1

---

templates/requirements.yml

This depends on https://github.com/mother-of-all-self-hosting/ansible-role-adguard-home/pull/2

Upgrade Adguard Home (v0.107.52-0 -> v0.107.56-0)

---

docs/services/adguard-home.md
docs/services/authelia.md
docs/services/authentik.md
docs/services/calibre-web.md
docs/services/couchdb.md
docs/services/forgejo.md
docs/services/gitea.md
docs/services/gotosocial.md
docs/services/ilmo.md
docs/services/keycloak.md
docs/services/keydb.md
docs/services/neko.md
docs/services/notfellchen.md
docs/services/paperless-ngx.md
docs/services/redis.md
docs/services/system.md
docs/services/traefik.md
docs/services/valkey.md
docs/uninstalling.md

This PR intends to adopt the practice at the MDAD project.

Replace sentences with "Warning" label with warning blockquotes based on GFM

---

docs/services/postgres.md

- Update postgres.md: add a copyright header
- Update postgres.md: copy from the MDAD project
- Update postgres.md: re-apply the existing strings specific to the MASH project
- Update postgres.md: replace version number of the link for psql documentation

Update postgres.md: copy from MDAD project

---

justfile

This makes the justfile compatible with rust-just.

Update justfile: use just_executable

---

docs/interoperability.md

For https://github.com/mother-of-all-self-hosting/mash-playbook/issues/388

Update docs/interoperability.md: the instruction to disable configuration for Docker

---

docs/services/infisical.md

The instruction about the mailer can be updated (I am working on it), but I would like to defer it to another PR as it is a different topic.

Update descriptions about configuring a Valkey instance on infisical.md

---

docs/services/ihatemoney.md
docs/supported-services.md
templates/group_vars_mash_servers
templates/requirements.yml
templates/setup.yml

I accidentally deleted the first  PR #352  so I'm reposting it now. I have implemented the suggestions from the DokuWiki PR. 
@spatterIight  and @spantaleev , thanks for your feedback - I hope the role is satisfactory now, otherwise I'll continue to rework it.
Ignore the version change of Tandoor - it has already been updated by the PR #433.

Add ihatemoney

---

docs/supported-services.md

Not quite clear why it has not been there; it seems it was just forgot to add it.

Update supported-services.md: add Notfellchen

---

templates/requirements.yml

See: https://codeberg.org/acioustick/ansible-role-joplin-server/src/tag/v3.3.4-1

Update joplin_server from v3.3.4-0 to v3.3.4-1

---

templates/group_vars_mash_servers

Inside `mash_playbook_postgres_managed_databases_auto_itemized`

Update group_vars_mash_servers: sort items alphabetically in the block for postgres

---

docs/services/grafana.md

This PR updates a variable in the documentation that is deprecated in the newest version of the Grafana role, and adds additional documentation regarding file provisioning with how to configure alerts and contact points.

Add documentation regarding Grafana file provisioning

---

docs/services/anonymousoverflow.md
docs/supported-services.md
templates/group_vars_mash_servers
templates/requirements.yml
templates/setup.yml

[AnonymousOverflow](https://github.com/httpjamesm/AnonymousOverflow) allows you to view StackOverflow threads without exposing your IP address, browsing habits, and other browser fingerprinting data to the website.

Add AnonymousOverflow

---

docs/services/gothub.md
docs/supported-services.md
templates/group_vars_mash_servers
templates/requirements.yml
templates/setup.yml

This PR intends to add [GotHub](https://codeberg.org/gothub/gothub).

Add GotHub

---

docs/services/jellyseerr.md
docs/supported-services.md
templates/group_vars_mash_servers
templates/requirements.yml
templates/setup.yml

This PR intends to add [Jellyseerr](https://github.com/Fallenbagel/jellyseerr).

Add jellyseerr

---

docs/services/immich-kiosk.md
docs/services/immich.md
docs/supported-services.md
templates/group_vars_mash_servers
templates/requirements.yml
templates/setup.yml

This PR intends to add [Immich Kiosk](https://immichkiosk.app), a software for displaying photos and videos on your [Immich](https://immich.app) server in highly customizable slideshows that run in browsers and other devices.
I have tested it on my server and confirmed it worked, exposing it to the internet like [this demo site](https://demo.immichkiosk.app/).

Add Immich Kiosk
