- docs/services/nextcloud.md
- group_vars/mash_servers
I've made some changes to add redis support to nextcloud. I still got some comments/questions. Could you guys give some feedback?
- `nextcloud_redis_enabled` is a new variable made in `group_vars/mash_servers`. I'm not sure if it's the right place to put it because I'm not very into ansible yet.
> Add redis support to nextcloud

- examples/hosts
Since there's already a service (Gitea) which recommends that SSH is changed to be on a non-standard port, it makes sense to add information about how to configure the playbook/Ansible to connect to a non-standard port
> Add info regarding the ansible_port varible

- docs/prerequisites.md
A bit nitpicky I'm aware, but I figure it's potentially misleading to refer to Red Hat-based distributions, as one could argue this would include Fedora, CentOS Stream, and derivatives.
Therefore I suggest an explicit reference to RHEL as well mentioning a CentOS replacement (Rocky Linux).
> Increase precision and accuracy with regard to Red Hat distributions

- .gitignore
- docs/services/n8n.md
- docs/supported-services.md
- group_vars/mash_servers
- requirements.yml
- setup.yml
This PR adds support to n8n using a custom role I made at ([kinduff/ansible-docker-n8n](https://github.com/kinduff/ansible-docker-n8n)).
Works like a charm, I have an instance up and running in production in my main server (works in my server, lol).
There's a big caveat and I need an advice:
The n8n Docker image uses UID and GID 1000 for the user `node` internally. This cannot be remapped as it executes `chown` and `setgroups` commands. I tried a good amount of things but all are related to modifying or extending their existing Docker image which is not ideal. Are there any other roles in this playbook that had this problem?
Besides that, works good if you specify in your config the UID and GID n8n needs:
```yml
n8n_uid: "1000"
n8n_gid: "1000"
```
> Adds support for n8n

- group_vars/mash_servers
Allows keycloak to start up before services that may depend on it.
> Changed startup priority for Keycloak

- docs/services/roundcube.md
- docs/supported-services.md
- group_vars/mash_servers
- requirements.yml
- setup.yml
This PR adds initial support for Roundcube.
The ansible role lives at
https://git.sr.ht/~sergiodj/ansible-role-roundcube ; I would really
appreciate any feedback you might have about it as well.
I did my tests using a local VM, and unfortunately I haven't been able
to test some of the more advanced stuff yet (like using a different
path prefix).  I'll see if I can perform some more extensive tests
meanwhile.
As I mentioned in the mash-playbook Matrix room, I did my best to try
to run the container as non-root but doing so proved to be harder than
expected.  For that reason, the UID/GID of the service is currently
set to `0`.  If you have any ideas/suggestions on how to improve this
specific situation, I'm all ears.
Thanks in advance.
> Add Roundcube

- docs/services/woodpecker-ci.md
It should now be possible to host Woodpecker CI under a subpath, so we
need to update the documentation to reflect that.
Closes #151
> Improve Woodpecker CI docs to mention subpath hosting

- docs/services/woodpecker-ci.md
Remove the (now unnecessary) warning saying that gRPC connections
don't work, and provide a better example on how to configure the
agent.
> Improve Woodpecker documentation regarding gRPC connections

- docs/services/adguard-home.md
Adguard Home can't perform first time setup without root. This PR documents a workaround for this issue by running the container as root initially and change the user back afterwards.
> Document workaround needed for Adguard Home

- templates/group_vars_mash_servers
Also supporting `gitea_container_additional_networks_custom`.
Solves https://github.com/mother-of-all-self-hosting/mash-playbook/issues/171
> support exim-relay in Gitea 

- docs/supported-services.md
I just found this playbook and was reading up, and realized that the link to the WG Easy project is too old, since then the author has moved it to a dedicated organization. This PR updates the link.
> Update project link for WG Easy

- VERSIONS.md
- docs/services/paperless-ngx.md
- docs/supported-services.md
- templates/group_vars_mash_servers
- templates/requirements.yml
- templates/setup.yml
As discussed in the chat, this role adds paperless-ngx but will not be able to run in a rootless container. This would probably need a fork of upstream. A warning of this is added to the docs.
> Add paperless-ngx 

- docs/services/calibre_web.md
- templates/group_vars_mash_servers
- templates/requirements.yml
- templates/setup.yml
submitting a role for Calibre-Web, based off [Linuxserver.io image](https://hub.docker.com/r/linuxserver/calibre-web) - which seems to be the ["official" image](https://github.com/janeczku/calibre-web?tab=readme-ov-file#docker-images).
unfortunately, unable to run rootless, but is set to run as the mash user internally like the LSIO images are able to.
> Add Calibre-Web role

- templates/group_vars_mash_servers
Add support in paperless for the exim-relay & generate [paperless-secret-key](https://docs.paperless-ngx.com/configuration/#PAPERLESS_SECRET_KEY).
This PR require that my [PR to the ansible-role-paperless](https://github.com/mother-of-all-self-hosting/ansible-role-paperless/pull/1) to be merged and the new version to be used in the MASH playbook.
> feat: paperless support exim-relay & generate paperless-secret-key

- templates/group_vars_mash_servers
Second try of adding the funkwhale watch imports service declaration to group vars after failing in #126
> Add funkwhale watch imports service to group vars #2

- templates/group_vars_mash_servers
This PR relates to my [PR to the ansible-role-paperless](https://github.com/mother-of-all-self-hosting/ansible-role-paperless/pull/7) to add Support for paperless-tika and gotenburg.
> feat(paperless): Add support for Paperless-tika & gotenburg

- docs/services/couchdb.md
- templates/group_vars_mash_servers
- templates/requirements.yml
- templates/setup.yml
This PR adds support for [CouchDB](https://couchdb.apache.org) via the [ansible-role-couchdb](https://github.com/Bergruebe/ansible-role-couchdb).
Currently it doesn't support traefik automatically, because I'm not familiar with traefik. If someone else finds the time to add the support, I would be happy to accept a PR.
> Add support for couchDB

- docs/developer-documentation.md
I tried to create an ansible-role for wallabag, and it was possible for me, who is still quite new to ansible, by just looking into the existing files and roles you already created. But it would have been much easier if there was a documentation on which steps are required to create and add a new service to this great playbook.
I'm not sure if any steps are required for `bin/versions.py` and `bin/optimize.py`.
It would be really great if someone could document how to use traefik in a role. I don't have the knowledge to do that.
> Add developer documentation

- VERSIONS.md
- docs/services/writefreely.md
- docs/supported-services.md
- templates/group_vars_mash_servers
- templates/requirements.yml
- templates/setup.yml
Following #12, I finally managed to create a writefreely role.
Please feel free to comment and add requests!
> Add Writefreely service

- docs/services/grafana.md
Fix for empty panels in grafana for some prometheus metrics. Solution from https://github.com/rfmoz/grafana-dashboards/issues/137
> Sync grafana datasource and prometheus scrape intervals.

- docs/services/gotosocial.md
Change link for split-domain deployments as the previous link leads to a 404 error
> Update gotosocial docs link

- templates/requirements.yml
point to ansible-role-calibre-web v.0.6.23-0
There is a bug affecting eBook conversion, but it does not seem to be limited to this new version of Calibre-Web (v.0.6.23) - it seems to be related to the LSIO mod, not the service; https://github.com/linuxserver/docker-calibre-web/issues/307 - so i'll go ahead and bump the requirement.
> Update requirements.yml - Calibre-Web

- templates/group_vars_mash_servers
Forgejo should use forgejo_container_additional_networks_auto instead
of forgejo_container_additional_networks otherwise the role will
overwrite custom networks added by the user.
> Fix Forgejo additional container network template

- docs/services/readeck.md
- templates/group_vars_mash_servers
- templates/requirements.yml
- templates/setup.yml
Readeck is a simple web application that lets you save the precious readable content of web pages you like and want to keep forever.
See it as a bookmark manager and a read later tool.
https://readeck.org
https://codeberg.org/readeck/readeck
please let me know if there are any issues, i am also running ```matrix-docker-ansible-deploy``` but that shouldn't affect anything hopefully?
> Add Readeck service

- docs/services/forgejo-runner.md
- docs/services/forgejo.md
- docs/services/woodpecker-ci.md
- docs/supported-services.md
- templates/group_vars_mash_servers
- templates/requirements.yml
- templates/setup.yml
Add support for [Forgejo Runner](https://code.forgejo.org/forgejo/runner).
Caveats:
- The software is still alpha, and not considered secure enough to be deployed in production.  I left a warning on the documentation.
- Unfortunately it's necessary to run the container as `root`, because upstream's Dockerfile will forcefully set `1000:1000` as the `UID/GID` and we need access to `/var/run/docker.sock`.
- Maybe this should use `docker-socket-proxy`?  Not sure how to integrate both.
- The registration process is not as streamlined as with [Gitea's runner](https://gitea.com/gitea/act_runner).  I had to do some `ExecPreStart` dance in the systemd service.  Hopefully that's not too problematic.
> Add Forgejo Runner service

- docs/services/stirling-pdf.md
- docs/supported-services.md
- templates/group_vars_mash_servers
- templates/requirements.yml
- templates/setup.yml
This PR adds [Stirling PDF](https://www.stirlingpdf.com), a tool to edit and convert PDFs.
The ansible role can be found [here](https://github.com/Bergruebe/ansible-role-stirling-pdf).
> add Stirling PDF

- templates/group_vars_mash_servers
Before this change the tandoor variables would always be in the optimized group_vars file. This PR fixes the issue.
> Add role-specific annotations in group_vars for tandoor

- docs/services/searxng.md
- docs/supported-services.md
- templates/group_vars_mash_servers
- templates/requirements.yml
- templates/setup.yml
This PR adds a new service for SearXNG.
Unfortunately, upstream doesn't version their images (and it seems like they've stopped versioning their regular software releases as well), so I decided to make the service always pull the `latest` tag.  I realize this is not ideal and am open to suggestions on how to approach this problem.
> Add SearXNG service

- docs/services/tsdproxy.md
- docs/supported-services.md
- templates/group_vars_mash_servers
- templates/requirements.yml
- templates/setup.yml
This PR adds support for [TSDProxy](https://almeidapaulopt.github.io/tsdproxy/). 
A special proxy, which publishes docker containers to your [Tailscale](tailscale.com) network (Tailnet).
> new service: TSDProxy

- docs/services/sonarr.md
- docs/supported-services.md
- templates/group_vars_mash_servers
- templates/requirements.yml
- templates/setup.yml
This PR adds Sonarr support. It has been tested as working. `sonarr_path_prefix` has not been tested.
https://github.com/spatterIight/ansible-role-sonarr/tree/main
The role configures Sonarr with security in mind by doing the following:
1. Running the container as a non-root user
2. Making the filesystem read-only
3. Dropping most capabilities
Unfortunately, due to upstream requirements, some admissions had to be made:
1. Several capabilities related to permissions are added to the container
- SETUID
- SETGID
- CHOWN
- FOWNER
- DAC_OVERRIDE
2. A `tmpfs` volume is mounted with `exec` permissions
You can read more about these upstream requirements in the documentation:
1. https://docs.linuxserver.io/misc/non-root/
2. https://docs.linuxserver.io/misc/read-only/
> Add Sonarr support

- justfile
This PR intends to make it possible to run just's "recipes" with `rust-just` etc.
> Make justfile compatible with just binaries other than "just"

- docs/services/backup-borg.md
- Copy from the MDAD playbook (https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/3de5bfa6a83618ac26bb815344686adff42b4cd7/docs/configuring-playbook-backup-borg.md)
- Fix the title: "Setting up … (optional)" is not common at the MASH playbook
> Update backup-borg.md: copy from the MDAD playbook

- docs/README.md
- docs/installing.md
- docs/just.md
- docs/playbook-tags.md
This PR intends to add docs/just.md and docs/playbook-tags.md by copying them from the MDAD project and edit them for the MASH project. I tried to be careful here not to mix up stuff related to Matrix, but it would be appreciated if the changes are reviewed, especially on be6bd0c8a03fb1920ec17b3169052052a5b35556 and f4cc701b041bf59a285dbbb2ccdbdfac79091d16. 51c3da3a47cf75cc842444c3f15616a49097bd1c should be fine.
> Add docs/just.md and docs/playbook-tags.md

- docs/ansible.md
This PR intends to update docs/ansible.md, in order to make it identical with the one on the MDAD project ([here](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/b6db2eaf15464d24c7b89f2d1cbd507936cb8482/docs/ansible.md)). This PR makes the number of both files' lines to 122.
> Update docs/ansible.md: make it identical with the one on the MDAD project

- docs/configuring-dns.md
- docs/configuring-playbook.md
- docs/getting-the-playbook.md
- docs/installing.md
- docs/prerequisites.md
This PR intends to update docs about installation process from setting up prerequisites, through configuring DNS record, getting a playbook, configuring it, to running the playbook to install services, based on the MDAD project's documentation.
> Update docs: installation process based on MDAD project

- docs/services/backup-borg.md
- docs/services/exim-relay.md
- docs/services/jitsi.md
- docs/services/postgres-backup.md
Linking to the roles instead of the project: because both those roles and the playbook are maintained by the MASH project, linking to the project is insistent.
> Update docs: introductions

- docs/services/etherpad.md
- docs/supported-services.md
- templates/group_vars_mash_servers
- templates/requirements.yml
- templates/setup.yml
This PR intends to add Etherpad, partly in case of [Etherpad on the MDAD project](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-etherpad.md) getting less relevant (or just pointless) after Element Call will practically replace Jitsi.
> Add Etherpad

- docs/services/ntfy.md
This has bugged me for a while as SchildiNext, therefore Element X Android too (both are client applications for Matrix), did not return an actionable error message on its UI, and I think it deserves clear instruction.
> Update ntfy.md: add the instruction to log in to the account with authentication enabled

- templates/group_vars_mash_servers
- Sort blocks from `# role-specific:adguard_home` to `# role-specific:yourls`  alphabetically, on the assumption that variables would neither cascade nor depend on its appearance order
- if other factors have been taken into consideration it should be detailed with a comment
- Add forgejo (`# role-specific:forgejo`) to `mash_playbook_hubsite_service_list_auto_itemized` thanks to clear view obtained by sorting.
> Tidy up group_vars_mash_servers

- docs/services/privatebin.md
- docs/supported-services.md
- templates/group_vars_mash_servers
- templates/requirements.yml
- templates/setup.yml
This PR intends to add [PrivateBin](https://privatebin.info/) ([ansible-role-privatebin](https://github.com/mother-of-all-self-hosting/ansible-role-privatebin)) to the playbook.
I've tested several scenarios (File system, MariaDB, PostgreSQL, with and without YOURLS, themes, file upload feature, under default domain with `/bin` and with its dedicated domain `bin.example.com`).
> Add PrivateBin

- .github/workflows/lock-threads.yml
- LICENSES/MIT.txt
The action will be used to lock issues and PRs to prevent necro-posting on closed ones which have not had any activity in the past year.
--
This action is available at https://github.com/marketplace/actions/lock-threads. I've found the similar one [here](https://github.com/truecharts/public/issues/11967#issuecomment-1732440253); it seems it is not the same action but it should work in a similar way.
> Add lock-threads.yml
